REM %1:DBA用户
REM %2:DBA用户的密码
REM %3:数据库联接字符串
REM 调用举例:CREATE_ALL_OBJECT.BAT ES_DBA CHANGE_ON_INSTALL ORA47 EA_PUB D:\ORACLE\ORADATA\ESIM60\
CALL CREATE_TABLE_PUB.BAT %1 %2 %3

REM CALL CREATE_VIEW_PUB.BAT %1 %2 %3

REM CALL CREATE_PROC_PUB.BAT %1 %2 %3

REM CALL CREATE_INIT_PUB.BAT %1 %2 %3

